/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "main.h"
#include "sytem_clock.h"
#include "bsp_lcd.h"
#include "ST7735.h"
#include "GFX_FUNCTIONS.h"
#include "SysTick_Delay.h"
#include "testimage.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void SystTick_Init(void);

int main(void)
{
  SystemClock_Output();

  SystemClock_Setup();

  SystTick_Init();

  BSP_LCD_Init();

  /* Loop forever */
  while (1)
  {
    fillScreen(BLACK);
    Delay_ms(1000);
    ST7735_SetRotation(0);
    testAll(); // test patterns

    // fill screen back o black
    fillScreen(BLACK);
    Delay_ms(1000);

//
//    ST7735_SetRotation(0);
//    ST7735_WriteString(0, 0, "Te iubesc mult Liz!", Font_11x18, RED,BLACK);
//    Delay_ms(2000);
//    fillScreen(BLACK);
//
//    ST7735_SetRotation(1);
//    ST7735_WriteString(0, 0, "Esti o Gugiugu, Chicorita mica", Font_7x10, GREEN,BLACK);
//    Delay_ms(2000);
//    fillScreen(BLACK);
//
//    ST7735_SetRotation(2);
//    ST7735_WriteString(0, 0, "O soricica mica :3", Font_11x18, GREEN,BLACK);
//    Delay_ms(2000);
//    fillScreen(BLACK);
//
//    ST7735_SetRotation(3);
//    ST7735_WriteString(0, 0, ">:*<", Font_16x26, YELLOW,BLACK);
//    Delay_ms(2000);
//    fillScreen(BLACK);

    ST7735_DrawImage(0, 0, ST7735_WIDTH, ST7735_HEIGHT, (uint16_t*)test_img_1);
    Delay_ms(3000);
    ST7735_DrawImage(0, 0, ST7735_WIDTH, ST7735_HEIGHT, (uint16_t*)test_img_2);
    Delay_ms(3000);
    ST7735_DrawImage(0, 0, ST7735_WIDTH, ST7735_HEIGHT, (uint16_t*)test_img_3);
    Delay_ms(3000);
//    for(int x = 0; x < ST7735_WIDTH; x++)
//    {
//        for(int y = 0; y < ST7735_HEIGHT; y++)
//        {
//            uint16_t color565 = test_img_be[y][x];
//            // fix endiness
//            color565 = ((color565 & 0xFF00) >> 8) | ((color565 & 0xFF) << 8);
//            ST7735_DrawPixel(x, y, color565);
//        }
//    }

    //ST7735_DrawImage(0, 0, ST7735_WIDTH, ST7735_HEIGHT, (uint16_t*)test_img_128x128);

    Delay_ms(2000);

    ST7735_SetRotation(1);
    ST7735_WriteString(0, 0, "TE IUBESC!!!! >:*<", Font_16x26, YELLOW,BLACK);
    Delay_ms(2000);
    fillScreen(BLACK);
  }
}


